### PR TITLE
PBI-216 Split ckeditor and vendor to seperate chunks

### PR DESCRIPTION
**Pull request by FreeJ1nG**
## Describe your changes
- Seperate ckeditor and other third-party libraries to separate chunks
- Optimizations:
  - Here is the build result *before* this change:
  image
  - Here is the build result *after* this change:
  image
  As we can see, the chunks are now split up more evenly, and the **heavy** CKEditor bundle is never loaded unless a user accesses some component that uses CKEditor
- I also installed [rollup-plugin-visualizer](https://www.npmjs.com/package/rollup-plugin-visualizer), which helped me decide which bundles should be split from the main bundle:
image
Here, we can see that CKEditor took up more than half of the application bundle, making it an easy decision to split it up from the main bundle
- What are the considerations of doing this? are there any cons that come along with splitting up the CKEditor chunk (and vendor chunk)?
  - Most modern browsers are able to do concurrent requests, meaning that chunk splitting is a good strategy **UNTIL** the threshold where the amount of chunks are larger than what the browser is able to request concurrently, in this case, since we are only splitting the chunks into three pieces, this shouldn't be a problem
  - CKEditor is a **LARGE** dependency that might not always be used, I see chunk splitting CKEditor as an absolute win here, the CKEditor component already lazy imports the CKEditor component

## Issue ticket number and link
- [ADU-216](https://linear.app/adudu/issue/ADU-216/chunk-splitting-to-seperate-large-bundles)

### CODE REVIEW

**Comment by ferryhieronimus** [comment]
This is a rather interesting PR. In theory, the chunks are now split more evenly. However, does this show noticeable improvement in performance? Or what metrics does it improve? Faster load times? Lower memory usage?

**Comment by edutjie** [comment]
Wow! great knowledge sharing and improvement Dru. It's so cool that Vite is able to do this kind of things, could you share the resource to learn vite can do build chunks seperation? And I also wonder do other build tools able to do this feature too?


In addition to Ferry's comment, I agree we should evaluate it quantitatively once we have setup our monitoring tools to have a concrete performance improvement.

**Comment by FreeJ1nG** [comment]
> This is a rather interesting PR. In theory, the chunks are now split more evenly. However, does this show noticeable improvement in performance? Or what metrics does it improve? Faster load times? Lower memory usage?

Good point, to answer both @ferryhieronimus  and @edutjie's inquiries, here is a screenshot of the assets that are loaded on first page load:
image

Let's focus on this:
image

Notice that CKEditor is not there, let's see what things were like previously:
image

This change is further highlighted when the end users have slow internet/device, here is a screenshot of large main bundle file over 3G connection:
Screenshot 2024-11-22 at 21 22 04

Let's compare that to the same connection with the change:
image

We can see that the first page load differs by a whopping ~4s, this can be further optimized by lazy loading the routes, which I'll be doing next week. Small improvements over time make the biggest of changes! I hope that this explains what I'm trying to do :)

**Comment by FreeJ1nG** [comment]
> Wow! great knowledge sharing and improvement Dru. It's so cool that Vite is able to do this kind of things, could you share the resource to learn vite can do build chunks seperation? And I also wonder do other build tools able to do this feature too?
> 
> In addition to Ferry's comment, I agree we should evaluate it quantitatively once we have setup our monitoring tools to have a concrete performance improvement.

Hey Edu! thank you 😄, it is cool indeed!
Chunk Splitting is a "well-known" (somewhat, albeit not very well understood by most people) concept that are available on most bundlers, Webpack, Rollup, etc are able to do this, here is a [link](https://vite.dev/guide/build.html#chunking-strategy) to read more about the topic

**Comment by valeelim** [comment]
Great PR @FreeJ1nG, with all the benefits, are there some known drawbacks to this "chunk splitting" technique, or why a project might not be suitable for this method?

**Review by valeelim — APPROVED** [review]
LGTM!

**Comment by FreeJ1nG** [comment]
> Great PR @FreeJ1nG, with all the benefits, are there some known drawbacks to this "chunk splitting" technique, or why a project might not be suitable for this method?

Hey @valeelim! thank you :D

Chunk splitting, while beneficial in optimizing web applications, isn't always the perfect solution for every project. Here are some potential drawbacks and situations where it might not be suitable:

1. Increased Initial Load Time
*Issue*: Splitting files into smaller chunks can sometimes increase the number of HTTP requests required to load an application. On older browsers or systems with poor HTTP/2 support, this can lead to slower performance.
*Consideration*: Projects targeting environments with limited HTTP/2 support might face challenges with chunk splitting.

2. Overhead in Chunk Management
*Issue*: Managing multiple chunks can add complexity. If chunks are not appropriately sized or grouped, it could lead to inefficient lazy loading and frequent switching between chunks.
*Consideration*: Projects with simple structures or minimal dynamic content might not benefit from the added complexity.

3. Cache Invalidation
*Issue*: Changes to one part of a split chunk might affect other chunks if they are not properly configured (e.g., vendor or runtime chunks). This can invalidate cached assets, reducing the benefit of browser caching.
*Consideration*: For projects where caching is critical, improper configuration can negate the benefits of chunk splitting.

4. Latency in User Experience
*Issue*: While chunk splitting can reduce the initial bundle size, excessive splitting may lead to delays in fetching dependent chunks when users navigate to new parts of the application.
*Consideration*: Applications requiring seamless transitions or real-time data might suffer from delayed content rendering.

5. Potential Code Duplication
*Issue*: If shared code (e.g., libraries or dependencies) is not appropriately extracted into a separate chunk, it may get duplicated across multiple chunks, inflating the overall size of the application.
*Consideration*: Projects with heavy dependency on shared modules might need meticulous configuration to avoid duplication.

6. Build Complexity
*Issue*: Implementing and maintaining an efficient chunk-splitting strategy can increase the complexity of the build process. Developers need to spend time analyzing usage patterns, optimizing chunk sizes, and tweaking configurations.
*Consideration*: Projects with tight deadlines or smaller teams might find the overhead challenging to manage.

Here are some examples where avoiding Chunk Splitting might make sense:
- Static Websites: Chunk splitting might not offer significant benefits for static or server-rendered websites with minimal interactivity.
- Small Applications: For applications with a small codebase, the added complexity of chunk splitting may outweigh its benefits.
- Non-JavaScript-Heavy Applications: If the application doesn’t rely heavily on JavaScript, the performance gains from chunk splitting may be minimal.

**Conclusion**
While chunk splitting is a powerful optimization tool, it’s not a one-size-fits-all solution. Projects need to carefully evaluate their specific requirements, user base, and deployment environment to determine if chunk splitting aligns with their performance and maintenance goals.

**Pull request merged**
