### PR TITLE
PBI-154-155 Email Status UI & Integration

### PR DESCRIPTION
**Pull request by FreeJ1nG**
## Describe your changes
- Add email status UI (Page + Components)
- Add testing for corresponding code
- Add backend integration for email status
- Here is a screenshot of the UI:
image

## Issue ticket number and link
- [ADU-154](https://linear.app/adudu/issue/ADU-154/ui-page-for-email-statuses)
- [ADU-155](https://linear.app/adudu/issue/ADU-155/integration-with-be)

### CODE REVIEW

**Review by valenciusap17 — APPROVED** [review]
Code looks simple and executed well, I don't think we have any problem here.  Good job handsome 🥇

**Comment by ferryhieronimus** [comment]
Could you also provide the screenshot(s) of the page?

**Comment by FreeJ1nG** [comment]
> Could you also provide the screenshot(s) of the page?

Done

**Comment by FreeJ1nG** [comment]
> Code looks simple and executed well, I don't think we have any problem here. Good job handsome 🥇

Thank you handsome 🥰

**Pull request merged**
