### PR TITLE
PBI-54: Typography

### PR DESCRIPTION
**Pull request by ferryhieronimus**
## Describe your changes
- Create test for typhography
- Add Typography element

## Issue ticket number and link
- ADU-54: https://linear.app/adudu/issue/ADU-54/typography

## Additional Notes
- This Typography component follows the [Material Design typographic scale](https://m2.material.io/design/typography/#type-scale) but without the BUTTON and OVERLINE
- All tests have passed. At the time this merge request was submitted, there was no static code analysis in place. I have attached this screenshot
- 
image

### CODE REVIEW

**Comment by valeelim** [comment]
ganteng 👌

**Comment by FreeJ1nG** [comment]
Also, it seems like you're not following the eslint rules we set in the repo, so please make sure that's fixed next time

```
➜  kg-procurement-ui git:(PBI-54-Typography) ✗ pnpm lint

> kg-procurement-ui@0.0.0 lint /Users/freejing/Documents/univ/ppl/kg-procurement-ui
> eslint .

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============

/Users/freejing/Documents/univ/ppl/kg-procurement-ui/src/components/atoms/typography/index.tsx
   1:1   error  Run autofix to sort these imports!       simple-import-sort/imports
   1:20  error  Missing file extension for "@/utils/cn"  import-x/extensions
   1:20  error  Strings must use singlequote             @stylistic/quotes
   1:32  error  Extra semicolon                          @stylistic/semi
   2:22  error  Strings must use singlequote             @stylistic/quotes
   2:44  error  Extra semicolon                          @stylistic/semi
   3:21  error  Strings must use singlequote             @stylistic/quotes
   3:47  error  Extra semicolon                          @stylistic/semi
   4:19  error  Strings must use singlequote             @stylistic/quotes
   4:26  error  Extra semicolon                          @stylistic/semi
   7:5   error  Strings must use singlequote             @stylistic/quotes
   8:5   error  Strings must use singlequote             @stylistic/quotes
   9:5   error  Strings must use singlequote             @stylistic/quotes
  10:5   error  Strings must use singlequote             @stylistic/quotes
  11:5   error  Strings must use singlequote             @stylistic/quotes
  12:5   error  Strings must use singlequote             @stylistic/quotes
  13:5   error  Strings must use singlequote             @stylistic/quotes
  14:5   error  Strings must use singlequote             @stylistic/quotes
  15:5   error  Strings must use singlequote             @stylistic/quotes
  16:5   error  Strings must use singlequote             @stylistic/quotes
  ```

**Comment by ferryhieronimus** [comment]
> Also, it seems like you're not following the eslint rules we set in the repo, so please do that before we merge
> 
> ```
> ➜  kg-procurement-ui git:(PBI-54-Typography) ✗ pnpm lint
> 
> > kg-procurement-ui@0.0.0 lint /Users/freejing/Documents/univ/ppl/kg-procurement-ui
> > eslint .
> 
> =============
> 
> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0
> 
> YOUR TYPESCRIPT VERSION: 5.6.2
> 
> Please only submit bug reports when using the officially supported version.
> 
> =============
> 
> /Users/freejing/Documents/univ/ppl/kg-procurement-ui/src/components/atoms/typography/index.tsx
>    1:1   error  Run autofix to sort these imports!       simple-import-sort/imports
>    1:20  error  Missing file extension for "@/utils/cn"  import-x/extensions
>    1:20  error  Strings must use singlequote             @stylistic/quotes
>    1:32  error  Extra semicolon                          @stylistic/semi
>    2:22  error  Strings must use singlequote             @stylistic/quotes
>    2:44  error  Extra semicolon                          @stylistic/semi
>    3:21  error  Strings must use singlequote             @stylistic/quotes
>    3:47  error  Extra semicolon                          @stylistic/semi
>    4:19  error  Strings must use singlequote             @stylistic/quotes
>    4:26  error  Extra semicolon                          @stylistic/semi
>    7:5   error  Strings must use singlequote             @stylistic/quotes
>    8:5   error  Strings must use singlequote             @stylistic/quotes
>    9:5   error  Strings must use singlequote             @stylistic/quotes
>   10:5   error  Strings must use singlequote             @stylistic/quotes
>   11:5   error  Strings must use singlequote             @stylistic/quotes
>   12:5   error  Strings must use singlequote             @stylistic/quotes
>   13:5   error  Strings must use singlequote             @stylistic/quotes
>   14:5   error  Strings must use singlequote             @stylistic/quotes
>   15:5   error  Strings must use singlequote             @stylistic/quotes
>   16:5   error  Strings must use singlequote             @stylistic/quotes
> ```

Alas! Does running `pnpm lint` automatically fix it?

**Comment by FreeJ1nG** [comment]
I added a commit to address the aforementioned issues btw

**Comment by FreeJ1nG** [comment]
> > Also, it seems like you're not following the eslint rules we set in the repo, so please do that before we merge
> > ```
> > ➜  kg-procurement-ui git:(PBI-54-Typography) ✗ pnpm lint
> > 
> > > kg-procurement-ui@0.0.0 lint /Users/freejing/Documents/univ/ppl/kg-procurement-ui
> > > eslint .
> > 
> > =============
> > 
> > WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> > 
> > You may find that it works just fine, or you may not.
> > 
> > SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0
> > 
> > YOUR TYPESCRIPT VERSION: 5.6.2
> > 
> > Please only submit bug reports when using the officially supported version.
> > 
> > =============
> > 
> > /Users/freejing/Documents/univ/ppl/kg-procurement-ui/src/components/atoms/typography/index.tsx
> >    1:1   error  Run autofix to sort these imports!       simple-import-sort/imports
> >    1:20  error  Missing file extension for "@/utils/cn"  import-x/extensions
> >    1:20  error  Strings must use singlequote             @stylistic/quotes
> >    1:32  error  Extra semicolon                          @stylistic/semi
> >    2:22  error  Strings must use singlequote             @stylistic/quotes
> >    2:44  error  Extra semicolon                          @stylistic/semi
> >    3:21  error  Strings must use singlequote             @stylistic/quotes
> >    3:47  error  Extra semicolon                          @stylistic/semi
> >    4:19  error  Strings must use singlequote             @stylistic/quotes
> >    4:26  error  Extra semicolon                          @stylistic/semi
> >    7:5   error  Strings must use singlequote             @stylistic/quotes
> >    8:5   error  Strings must use singlequote             @stylistic/quotes
> >    9:5   error  Strings must use singlequote             @stylistic/quotes
> >   10:5   error  Strings must use singlequote             @stylistic/quotes
> >   11:5   error  Strings must use singlequote             @stylistic/quotes
> >   12:5   error  Strings must use singlequote             @stylistic/quotes
> >   13:5   error  Strings must use singlequote             @stylistic/quotes
> >   14:5   error  Strings must use singlequote             @stylistic/quotes
> >   15:5   error  Strings must use singlequote             @stylistic/quotes
> >   16:5   error  Strings must use singlequote             @stylistic/quotes
> > ```
> 
> Alas! Does running `pnpm lint` automatically fix it?

No, `pnpm lint` only shows all the errors/warnings, to fix the issues, you'll have to run the command with the `--fix` flag

```
➜  kg-procurement-ui git:(PBI-54-Typography) pnpm lint --fix   

> kg-procurement-ui@0.0.0 lint /Users/freejing/Documents/univ/ppl/kg-procurement-ui
> eslint . "--fix"
```

**Comment by FreeJ1nG** [comment]
I think we should add husky so that unlinted code can't be pushed

**Comment by FreeJ1nG** [comment]
LGTM! Let's merge

**Pull request merged**
