### PR TITLE
Setup Vitest

### PR DESCRIPTION
**Pull request by FreeJ1nG**
This PR integrates Vitest and React Testing Library to this repository

Some main points:
- [Vitest](https://vitest.dev/) is used as the test executor, helping with environment setup, etc
- [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) is used to setup the React DOM and other testing utilities that relates to react
- Setup of initial tests can be seen in `./src/main.test.tsx` and`./src/routes/__tests__/index.test.tsx`

Feel free to voice or opinions or thoughts :D

Here are some example of the test runs:
```
➜  kg-procurement-ui git:(andrew/setup-vitest) pnpm test

> kg-procurement-ui@0.0.0 test /Users/freejing/Documents/univ/ppl/kg-procurement-ui
> vitest


 DEV  v2.1.1 /Users/freejing/Documents/univ/ppl/kg-procurement-ui

 ✓ src/main.test.tsx (1)
 ✓ src/routes/__tests__/index.test.tsx (1)

 Test Files  2 passed (2)
      Tests  2 passed (2)
   Start at  16:34:31
   Duration  756ms (transform 41ms, setup 328ms, collect 137ms, tests 35ms, environment 638ms, prepare 120ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

### CODE REVIEW

**Comment by ferryhieronimus** [comment]
Looks great. One note: you also changed the routes and other files. In the future you might consider separating them but since we are in early development, that’s okay

**Comment by FreeJ1nG** [comment]
> Looks great. One note: you also changed the routes and other files. In the future you might consider separating them but since we are in early development, that’s okay

So since our app won't have a large variety of routes, what I had in mind was the use of [flat routes](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#flat-routes)

**Comment by bryannaufal** [comment]
Could you explain why you chose jsdom over Happy-DOM for the test environment?

**Comment by valenciusap17** [comment]
> Could you explain why you chose jsdom over Happy-DOM for the test environment?

Is it because jsdom has more plugins that extend support for various web API's? Great code Andrew btw 😄

**Comment by FreeJ1nG** [comment]
> > Could you explain why you chose jsdom over Happy-DOM for the test environment?
> 
> Is it because jsdom has more plugins that extend support for various web API's? Great code Andrew btw 😄

Yeah, `happy-dom` is the faster alternative to jsdom, but as mentioned in [this](https://github.com/vitest-dev/vitest/discussions/1607) issue, it seems that some people encountered issues with happy-dom, I wanted to be on the safe-side and just use jsdom

CC: @valenciusap17 @bryannaufal

**Pull request merged**
