### PR TITLE
PBI-69: Chart

### PR DESCRIPTION
**Pull request by FreeJ1nG**
## Describe your changes
Added Chart component (alongside Card component)

## Issue ticket number and link
ADU-69: https://linear.app/adudu/issue/ADU-69/chart

### CODE REVIEW

**Comment by FreeJ1nG** [comment]
So i want to move away from the current components setup, where we have `@/src/components/atoms/some-component/index.tsx` and `@/src/components/atoms/some/components/index.test.tsx` to `@/src/components/atoms/some-component.tsx` and `@/src/components/atoms/__tests__/some-component.test.tsx`, as can be seen in the changes

I don't see any merit in having `/some-component/index.tsx` since we'll never really have anything other than index.tsx inside the component folder anyway

**Comment by FreeJ1nG** [comment]
Also, i chose to move away to `happy-dom` since it supports TailwindCSS transforms in the testing environment, while JSDom gave an error of "Unable to parse CSS stylesheet"

**Comment by ferryhieronimus** [comment]
> So i want to move away from the current components setup, where we have `@/src/components/atoms/some-component/index.tsx` and `@/src/components/atoms/some/components/index.test.tsx` to `@/src/components/atoms/some-component.tsx` and `@/src/components/atoms/__tests__/some-component.test.tsx`, as can be seen in the changes
> 
> I don't see any merit in having `/some-component/index.tsx` since we'll never really have anything other than index.tsx inside the component folder anyway

In the future, as the number of components increases significantly, I think it would be better to colocate the code and its corresponding tests in the same directory, rather than grouping them all together in one place. However, I recall seeing that the `__tests__` directory is commonly used for tests, but I'm not entirely sure how to integrate that with the current directory structure

**Comment by FreeJ1nG** [comment]
> > So i want to move away from the current components setup, where we have `@/src/components/atoms/some-component/index.tsx` and `@/src/components/atoms/some/components/index.test.tsx` to `@/src/components/atoms/some-component.tsx` and `@/src/components/atoms/__tests__/some-component.test.tsx`, as can be seen in the changes
> > I don't see any merit in having `/some-component/index.tsx` since we'll never really have anything other than index.tsx inside the component folder anyway
> 
> In the future, as the number of components increases significantly, I think it would be better to colocate the code and its corresponding tests in the same directory, rather than grouping them all together in one place. However, I recall seeing that the `__tests__` directory is commonly used for tests, but I'm not entirely sure how to integrate that with the current directory structure

I don't agree with this, even with 50+ components, I find looking up `some-component.tsx` to be more convenient than `some-component/index.tsx`

**Pull request merged**
